// ============================================================================
// User Preferences & Profile Types
// ============================================================================

export interface UserPreferences {
  styles?: string[];
  colors?: string[];
  temperature_sensitivity?: number; // -2 (very cold) to +2 (very warm)
  preferred_materials?: string[];
  disliked_materials?: string[];
  fit_preference?: 'Slim' | 'Regular' | 'Oversized';
}

export interface Profile {
  id: string;
  name: string | null;
  region: string | null;
  full_body_model_url: string | null;
  preferences: UserPreferences | null;
}

// ============================================================================
// Clothing Item Types (Enhanced for Task 1.1)
// ============================================================================

export type ClothingType = 
  | 'Outerwear'
  | 'Top'
  | 'Bottom'
  | 'Footwear'
  | 'Accessory'
  | 'Headwear';

export type ClothingMaterial = 
  | 'Cotton'
  | 'Wool'
  | 'Synthetic'
  | 'Gore-Tex'
  | 'Fleece'
  | 'Leather'
  | 'Denim'
  | 'Silk'
  | 'Linen'
  | 'Polyester'
  | 'Nylon';

export type DressCode = 
  | 'Casual'
  | 'Business Casual'
  | 'Formal'
  | 'Athletic'
  | 'Loungewear';

/**
 * Enhanced Clothing Item Interface (Task 1.1)
 * Represents a single item in the user's virtual wardrobe
 */
export interface IClothingItem {
  id: number;
  user_id: string;
  name: string;
  type: ClothingType;
  category: string | null; // Legacy field, kept for backwards compatibility
  color: string | null;
  material: string | null; // AI may leave this blank until we analyze the item
  insulation_value: number | null; // 0-10 scale, higher = warmer
  last_worn: string | null; // ISO date string from database
  image_url: string;
  season_tags: string[] | null;
  style_tags: string[] | null;
  dress_code: DressCode[] | string[]; // Allow string array for flexibility
  created_at: string;
  // Enhanced AI-generated properties for better outfit recommendations
  pattern?: string | null;
  fit?: string | null;
  style?: string | null;
  occasion?: string[] | null;
  description?: string | null;
  favorite?: boolean;
  wear_count?: number;
}

/**
 * Legacy type for backwards compatibility
 */
export type ClothingItem = {
  id: number;
  user_id: string;
  category: string | null;
  color: string | null;
  season_tags: string[] | null;
  style_tags: string[] | null;
  image_url: string;
  created_at: string;
  last_used_date: string | null;
};

// ============================================================================
// Outfit Types
// ============================================================================

export interface Outfit {
  id: number;
  created_at: string;
  feedback: number | null;
  outfit_items: {
    clothing_items: {
      id: number;
      image_url: string;
      category: string | null;
    };
  }[];
}

// ============================================================================
// Weather & Environment Types (Task 3.x)
// ============================================================================

export interface WeatherData {
  temperature: number;
  feels_like: number; // Apparent temperature (Task 3.2)
  humidity: number;
  wind_speed: number;
  uv_index: number; // Task 3.1
  air_quality_index: number; // Task 3.1
  pollen_count: number; // Task 3.1
  weather_condition: string;
  timestamp: Date;
  season?: string; // Current season based on date and location
  season_description?: string; // Detailed season description
  city?: string; // Detected city name
}

export interface WeatherAlert {
  type: 'UV' | 'AQI' | 'Pollen';
  severity: 'low' | 'moderate' | 'high';
  message: string;
  recommendation?: string;
}

// ============================================================================
// Recommendation Types (Task 1.4, 2.4, 3.3)
// ============================================================================

export interface RecommendationContext {
  weather: WeatherData;
  user_preferences?: UserPreferences;
}

export interface RecommendationConstraints {
  dress_code?: DressCode;
  weather_alerts?: WeatherAlert[];
  min_days_since_worn?: number;
}

export interface RecommendationDebugEvent {
  stage: string;
  timestamp: string;
  meta?: Record<string, unknown>;
}

export interface RecommendationDiagnostics {
  requestId: string;
  warnings: string[];
  events: RecommendationDebugEvent[];
  summary?: {
    wardrobeCount?: number;
    missingInsulationCount?: number;
    filterCounts?: Record<string, number>;
    selectedItemIds?: Array<number | string>;
  };
}

export interface OutfitRecommendation {
  items: IClothingItem[];
  confidence_score: number;
  reasoning: string;
  // A more detailed, user-facing explanation generated by the recommendation engine
  detailed_reasoning?: string;
  missing_items?: string[];
  alerts?: WeatherAlert[];
  context: RecommendationContext;
}

export interface RecommendationApiPayload {
  recommendation: {
    outfit: IClothingItem[];
    confidence_score: number;
    reasoning: string;
    detailed_reasoning?: string | null;
    missing_items?: string[];
    dress_code: string;
    weather_alerts: WeatherAlert[];
    id?: string | number | null;
    outfit_visual_urls?: string[];
  };
  weather: WeatherData;
  alerts: WeatherAlert[];
}

// ============================================================================
// Feedback & Learning Types (Task 4.x)
// ============================================================================

export interface RecommendationFeedback {
  recommendation_id: string;
  is_liked: boolean;
  reason?: string;
  weather_conditions?: WeatherData;
  created_at: Date;
}

// ============================================================================
// API Response Types
// ============================================================================

export interface ValidationError {
  field: string;
  message: string;
}

export interface ApiResponse<T> {
  success: boolean;
  data?: T;
  error?: string;
  message?: string;
  validation_errors?: ValidationError[];
}

export interface PaginatedResponse<T> {
  data: T[];
  total: number;
  page: number;
  per_page: number;
  total_pages: number;
}

// ============================================================================
// AI Analysis Types (New)
// ============================================================================

export interface ClothingAnalysis {
  style: string;
  formality: string;
  season_suitability: string;
  color_harmony: string[];
  occasion_fit: string[];
}

export interface OutfitValidation {
  isValid: boolean;
  score: number;
  issues: string[];
  suggestions: string[];
  problemItemId?: number;
}

export interface AIOutfitRecommendation {
  outfit: IClothingItem[];
  validationScore: number;
  iterations: number;
  analysisLog: string[];
  reasoning: string;
}