'use client';

import { motion } from 'framer-motion';
import { cn } from '@/lib/utils';
import { ReactNode } from 'react';

export interface StickerBadgeProps {
  type?: 'success' | 'warning' | 'error' | 'info' | 'primary' | 'ai-generated';
  text: string;
  icon?: ReactNode;
  animate?: boolean;
  className?: string;
}

const stickerStyles = {
  success: 'sticker-success',
  warning: 'sticker-warning',
  error: 'sticker-error',
  info: 'sticker-info',
  primary: 'bg-primary text-primary-foreground border-2 border-primary',
  'ai-generated': 'bg-accent-purple text-white border-2 border-accent-purple',
};

export function StickerBadge({
  type = 'info',
  text,
  icon,
  animate = false,
  className,
}: StickerBadgeProps) {
  const Component = animate ? motion.div : 'div';
  
  return (
    <Component
      className={cn(
        'sticker inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-sm font-medium shadow-sticker',
        stickerStyles[type],
        className
      )}
      {...(animate ? {
        initial: { scale: 0, rotate: -12 },
        animate: { scale: 1, rotate: 0 },
        transition: {
          type: 'spring',
          stiffness: 260,
          damping: 15,
        },
      } : {})}
    >
      {icon && <span className="text-base">{icon}</span>}
      <span>{text}</span>
    </Component>
  );
}

export interface NotificationProps {
  type: 'success' | 'error' | 'warning' | 'info';
  title: string;
  message?: string;
  action?: {
    label: string;
    onClick: () => void;
  };
  onDismiss?: () => void;
}

export function PapercraftNotification({
  type,
  title,
  message,
  action,
  onDismiss,
}: NotificationProps) {
  const icons = {
    success: '🎉',
    error: '😱',
    warning: '⚠️',
    info: '💡',
  };
  
  const stickerType = type === 'error' ? 'error' : 
                      type === 'warning' ? 'warning' :
                      type === 'success' ? 'success' : 'info';

  return (
    <motion.div
      initial={{ opacity: 0, y: -20, scale: 0.95 }}
      animate={{ opacity: 1, y: 0, scale: 1 }}
      exit={{ opacity: 0, scale: 0.95 }}
      transition={{
        type: 'spring',
        stiffness: 260,
        damping: 20,
      }}
      className={cn(
        'sticker relative p-4 rounded-2xl shadow-lg max-w-md',
        `sticker-${stickerType}`
      )}
    >
      <div className="flex items-start gap-3">
        <span className="text-2xl flex-shrink-0">{icons[type]}</span>
        
        <div className="flex-1 min-w-0">
          <h4 className="font-heading text-base font-semibold mb-1">{title}</h4>
          {message && (
            <p className="text-sm opacity-90">{message}</p>
          )}
          
          {action && (
            <button
              onClick={action.onClick}
              className="mt-2 text-sm font-medium underline hover:no-underline"
            >
              {action.label}
            </button>
          )}
        </div>
        
        {onDismiss && (
          <button
            onClick={onDismiss}
            className="flex-shrink-0 w-6 h-6 rounded-full hover:bg-black/10 flex items-center justify-center transition-colors"
          >
            ×
          </button>
        )}
      </div>
    </motion.div>
  );
}

export function ProvenanceBadge({
  type = 'ai-generated',
  model,
  timestamp,
  className,
}: {
  type?: 'ai-generated' | 'ai-enhanced';
  model?: string;
  timestamp?: string;
  className?: string;
}) {
  return (
    <div
      className={cn(
        'sticker inline-flex items-center gap-2 px-3 py-1.5 rounded-xl text-xs font-medium bg-accent-purple text-white border-2 border-accent-purple shadow-sticker',
        className
      )}
      title={`Generated by ${model || 'AI'} on ${timestamp ? new Date(timestamp).toLocaleString() : 'unknown date'}`}
    >
      <span className="text-sm">✨</span>
      <div className="flex flex-col items-start">
        <span className="font-semibold">
          {type === 'ai-generated' ? 'AI Generated' : 'AI Enhanced'}
        </span>
        {model && (
          <span className="opacity-80 text-[10px]">{model}</span>
        )}
      </div>
    </div>
  );
}

export function WearCountBadge({
  count,
  lastWorn,
  className,
}: {
  count: number;
  lastWorn?: string | null;
  className?: string;
}) {
  const isRecent = lastWorn && 
    new Date(lastWorn) > new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
  
  return (
    <div className={cn('inline-flex items-center gap-1', className)}>
      <StickerBadge
        type={count === 0 ? 'warning' : isRecent ? 'success' : 'info'}
        text={`${count}× worn`}
        icon={count === 0 ? '🆕' : isRecent ? '🔥' : '👕'}
      />
      
      {lastWorn && (
        <span className="text-xs text-tertiary-label">
          {new Date(lastWorn).toLocaleDateString()}
        </span>
      )}
    </div>
  );
}

export function FavoriteBadge({
  isFavorite,
  onToggle,
  className,
}: {
  isFavorite: boolean;
  onToggle?: () => void;
  className?: string;
}) {
  return (
    <motion.button
      className={cn(
        'sticker px-2 py-1 rounded-lg text-base transition-all',
        isFavorite ? 'sticker-warning' : 'bg-muted text-muted-foreground',
        onToggle && 'cursor-pointer hover:scale-110',
        className
      )}
      onClick={onToggle}
      whileTap={onToggle ? { scale: 0.9 } : undefined}
      title={isFavorite ? 'Remove from favorites' : 'Add to favorites'}
    >
      {isFavorite ? '⭐' : '☆'}
    </motion.button>
  );
}
